execute as @a at @s positioned ^^1.5^1 run event entity @e[r=2,family=lookat] spotted
execute as @a at @s positioned ^^1.5^2 run event entity @e[r=2,family=lookat] spotted
execute as @a at @s positioned ^^1.5^3 run event entity @e[r=2,family=lookat] spotted
execute as @a at @s positioned ^^1.5^4 run event entity @e[r=2,family=lookat] spotted
execute as @a at @s positioned ^^1.5^5 run event entity @e[r=2.5,family=lookat] spotted
execute as @a at @s positioned ^^1.5^6 run event entity @e[r=2.5,family=lookat] spotted
execute as @a at @s positioned ^^1.5^1 run event entity @e[r=7.5,family=lookaat] spotted
execute as @a at @s positioned ^^1.5^7 run event entity @e[r=2.5,family=lookat] spotted
execute as @a at @s positioned ^^1.5^8 run event entity @e[r=2.5,family=lookat] spotted
execute as @a at @s positioned ^^1.5^9 run event entity @e[r=2.5,family=lookat] spotted
execute as @a at @s positioned ^^1.5^10 run event entity @e[r=2.5,family=lookat] spotted
execute as @a at @s positioned ^^1.5^11 run event entity @e[r=2.5,family=lookat] spotted
execute as @a at @s positioned ^^1.5^12 run event entity @e[r=2.5,family=lookat] spotted
execute as @a at @s positioned ^^1.5^13 run event entity @e[r=2.5,family=lookat] spotted
execute as @a at @s positioned ^^1.5^14 run event entity @e[r=2.5,family=lookat] spotted
execute as @a at @s positioned ^^1.5^15 run event entity @e[r=2.5,family=lookat] spotted
execute as @a at @s positioned ^^1.5^16 run event entity @e[r=2.5,family=lookat] spotted
execute as @a at @s positioned ^^1.5^17 run event entity @e[r=2.5,family=lookat] spotted
execute as @a at @s positioned ^^1.5^18 run event entity @e[r=2.5,family=lookat] spotted
execute as @a at @s positioned ^^1.5^19 run event entity @e[r=2.5,family=lookat] spotted
execute as @a at @s positioned ^^1.5^20 run event entity @e[r=2.5,family=lookat] spotted
execute as @a at @s positioned ^^1.5^21 run event entity @e[r=2.5,family=lookat] spotted
execute as @a at @s positioned ^^1.5^22 run event entity @e[r=2.5,family=lookat] spotted
execute as @a at @s positioned ^^1.5^23 run event entity @e[r=2.5,family=lookat] spotted
execute as @a at @s positioned ^^1.5^24 run event entity @e[r=2.5,family=lookat] spotted
execute as @a at @s positioned ^^1.5^25 run event entity @e[r=2.5,family=lookat] spotted
execute as @a at @s positioned ^^1.5^26 run event entity @e[r=2.5,family=lookat] spotted
execute as @a at @s positioned ^^1.5^27 run event entity @e[r=2.5,family=lookat] spotted
execute as @a at @s positioned ^^1.5^28 run event entity @e[r=2.5,family=lookat] spotted
execute as @a at @s positioned ^^1.5^29 run event entity @e[r=2.5,family=lookat] spotted
execute as @a at @s positioned ^^1.5^30 run event entity @e[r=2.5,family=lookat] spotted
execute as @a at @s positioned ^^1.5^31 run event entity @e[r=2.5,family=lookat] spotted
execute as @a at @s positioned ^^1.5^32 run event entity @e[r=2.5,family=lookat] spotted
